//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConcesionarioCutre
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Coch()
        {
            this.Operacions = new HashSet<Operacion>();
        }
    
        public int ID { get; set; }
        public string MARCA { get; set; }
        public string MODELO { get; set; }
        public Nullable<int> NUM_PUERTAS { get; set; }
        public string COLOR { get; set; }
        public Nullable<int> KILOMETROS { get; set; }
        public string TIPO { get; set; }
        public Nullable<int> GARANTIA { get; set; }
        public string FOTOGRAFIA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operacion> Operacions { get; set; }
    }
}
